# Server configuration.
server:
  # The minimum number of replicas.
  replicas: 1

  strategy:
    type: Recreate

  # Ingress configuration.
  ingress:
    external:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        kubernetes.io/ingress.allow-http: 'false'
        kubernetes.io/tls-acme: 'true'
        nginx.ingress.kubernetes.io/proxy-buffering: 'on'
        nginx.ingress.kubernetes.io/proxy-buffer-size: '16k'
        nginx.ingress.kubernetes.io/use-regex: "true"
      hosts:
        - fintech-landings.dev.cluster.daymarket.uz
      mainPaths:
        - path: / # Тут пишутся конкретные пути по которым можно открыть ваш фронт корня достаточно чтобы открывать по всем, но иногда нужно на разные урлы вешать разные приложения
          pathType: ImplementationSpecific
          port: 80
      additionalPaths: []

  # NodeSelector configuration of the validators.
  nodeSelector:
    app_type: apps
  autoscaling:
    enabled: true
    replicas:
      min: 3
      max: 10
    targetCPU: 10
    targetRAM: 256Mi

  # Tolerations of the validators pods.
  tolerations:
    - key: app_type
      operator: Equal
      value: apps
      effect: NoSchedule